'use strict';
const $=id=>document.getElementById(id);
const base={3:[['кот','🐱'],['дом','🏠'],['сок','🧃'],['мак','🌺'],['сыр','🧀'],['кит','🐋'],['мяч','⚽'],['лес','🌲'],['нос','👃'],['лук','🧅']],4:[['мама','👩'],['папа','👨'],['рука','✋'],['лиса','🦊'],['рыба','🐟'],['роза','🌹'],['сова','🦉'],['нога','🦵'],['луна','🌙'],['коза','🐐']],5:[['кошка','🐈'],['шапка','🧢'],['чашка','☕'],['книга','📖'],['лимон','🍋'],['белка','🐿️'],['сумка','👜'],['ложка','🥄'],['банан','🍌'],['арбуз','🍉']]};
const vowels='аеёиоуыэюя';
let level=Number(localStorage.getItem('ss-level')||3),style=localStorage.getItem('ss-style')||'normal';if(style==='hand')style='handLower';
let progress=JSON.parse(localStorage.getItem('ss-progress')||'{}'),custom=JSON.parse(localStorage.getItem('ss-custom')||'[]');
let current=null,usedHint=false,markedThisTurn=false,confirmationTimer=null,sessionWords=[],sessionIndex=0;
function all(){const p=base[level].slice();custom.forEach(w=>{if([...w].length===level&&!p.some(x=>x[0]===w))p.push([w,'📖']);});return p;}
function st(w){const old=progress[w]||{};return{self:Number(old.self||0),mastered:Boolean(old.mastered),masteredAt:Number(old.masteredAt||0)};}
function save(){localStorage.setItem('ss-progress',JSON.stringify(progress));localStorage.setItem('ss-custom',JSON.stringify(custom));}
function queue(){const available=all().map(x=>x[0]);let q=JSON.parse(localStorage.getItem('ss-queue-'+level)||'null');if(!Array.isArray(q))q=available.slice(0,5);q=q.filter(w=>available.includes(w));while(q.length<5){const n=available.find(w=>!q.includes(w));if(!n)break;q.push(n);}const ready=q.filter(w=>st(w).mastered);if(ready.length>=3){const fresh=available.find(w=>!q.includes(w)&&!st(w).mastered);if(fresh){const oldest=ready.slice().sort((a,b)=>{const at=st(a).masteredAt||Number.MAX_SAFE_INTEGER,bt=st(b).masteredAt||Number.MAX_SAFE_INTEGER;return at-b||q.indexOf(a)-q.indexOf(b);})[0];q=q.map(w=>w===oldest?fresh:w);}}localStorage.setItem('ss-queue-'+level,JSON.stringify(q));return q;}
function shown(w){const lower=w.toLocaleLowerCase('ru');if(style==='upper'||style==='handUpper')return lower.toLocaleUpperCase('ru');if(style==='title'||style==='handTitle')return lower.charAt(0).toLocaleUpperCase('ru')+lower.slice(1);return lower;}
function render(w,target=$('word')){target.replaceChildren(...[...shown(w)].map(ch=>{const s=document.createElement('span');s.textContent=ch;s.className=vowels.includes(ch.toLowerCase())?'vowel':/\p{L}/u.test(ch)?'consonant':'sign';return s;}));target.classList.toggle('hand',style.startsWith('hand'));}
function speak(text,rate=.72){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';u.rate=rate;speechSynthesis.speak(u);}
function hideConfirmation(){clearTimeout(confirmationTimer);$('confirmation').classList.remove('show');$('readOk').classList.remove('done');}
function resetTurn(){hideConfirmation();usedHint=false;markedThisTurn=false;$('readOk').disabled=false;$('readOk').title='Прочитал сам';$('confirmation').textContent='';}
function showSessionWord(){const w=sessionWords[sessionIndex];current=all().find(x=>x[0]===w)||all()[0];render(current[0]);$('pic').textContent=current[1];$('pic').hidden=true;$('reward').textContent='';resetTurn();}
function startSession(){sessionWords=queue().slice(0,5);sessionIndex=0;$('finishView').hidden=true;$('readingView').hidden=false;showSessionWord();}
function finishSession(){hideConfirmation();if('speechSynthesis'in window)speechSynthesis.cancel();$('readingView').hidden=true;$('finishView').hidden=false;}
function audioHelp(){if(!current)return;if(!markedThisTurn){usedHint=true;$('readOk').disabled=true;}speak(current[0],.72);}
function showPicture(){if(!current)return;if(!markedThisTurn){usedHint=true;$('readOk').disabled=true;}$('pic').hidden=false;}
function showConfirmation(justMastered){clearTimeout(confirmationTimer);$('confirmation').textContent=justMastered?'Слово освоено':'Засчитано';$('confirmation').classList.add('show');$('readOk').classList.add('done');confirmationTimer=setTimeout(()=>{$('confirmation').classList.remove('show');$('readOk').classList.remove('done');},1400);}
function markIndependent(){if(!current||usedHint||markedThisTurn)return;const s=st(current[0]),wasMastered=s.mastered;s.self=Math.min(3,s.self+1);s.mastered=s.self>=3;if(s.mastered&&!wasMastered)s.masteredAt=Date.now();progress[current[0]]=s;save();markedThisTurn=true;$('readOk').disabled=true;$('readOk').title=s.mastered?'Слово освоено':'Засчитано';showConfirmation(!wasMastered&&s.mastered);}
function next(){if(!current)return;if(sessionIndex>=sessionWords.length-1){finishSession();return;}sessionIndex++;showSessionWord();}
$('help').onclick=audioHelp;$('showPicture').onclick=showPicture;$('readOk').onclick=markIndependent;$('next').onclick=next;$('continue').onclick=startSession;
const styleLabels={normal:'абв',title:'Абв',upper:'АБВ',handLower:'абв',handTitle:'Абв',handUpper:'АБВ'};
function styleRender(){const hand=style.startsWith('hand');$('styleSelect').textContent=styleLabels[style]||'абв';$('styleSelect').classList.toggle('hand-preview',hand);document.querySelectorAll('.style-option').forEach(b=>b.classList.toggle('selected',b.dataset.style===style));}
function closeStyleMenu(){$('styleMenu').hidden=true;$('styleSelect').setAttribute('aria-expanded','false');}
function parentRender(){const q=queue();$('queue').replaceChildren(...q.map(w=>{const d=document.createElement('div'),s=st(w);d.className='word-row';const status=s.mastered?'Освоено':`${s.self}/3`;d.innerHTML='<strong>'+w+'</strong><span class="status">'+status+'</span>';return d;}));const mastered=all().map(x=>x[0]).filter(w=>st(w).mastered);if(mastered.length){$('mastered').replaceChildren(...mastered.map(w=>{const d=document.createElement('div');d.className='word-row mastered-row';d.innerHTML='<strong>'+w+'</strong><span class="status">✓ Освоено</span>';return d;}));}else{$('mastered').innerHTML='<div class="empty">Пока нет освоенных слов.</div>';}$('level').value=String(level);styleRender();}
$('parentOpen').onclick=()=>{$('childView').hidden=true;$('parentView').hidden=false;parentRender();};$('parentBack').onclick=()=>{closeStyleMenu();$('parentView').hidden=true;$('childView').hidden=false;if(current)render(current[0]);};
$('styleSelect').onclick=()=>{const opening=$('styleMenu').hidden;$('styleMenu').hidden=!opening;$('styleSelect').setAttribute('aria-expanded',String(opening));};
document.querySelectorAll('.style-option').forEach(b=>b.onclick=()=>{style=b.dataset.style;localStorage.setItem('ss-style',style);if(current)render(current[0]);styleRender();closeStyleMenu();});
document.addEventListener('click',e=>{if(!$('letterStyle').contains(e.target))closeStyleMenu();});
$('level').onchange=e=>{level=Number(e.target.value);localStorage.setItem('ss-level',String(level));startSession();parentRender();};
$('addWord').onclick=()=>{const w=$('customWord').value.trim().toLowerCase().replace(/[^\p{L}-]/gu,'');if([...w].length<3)return;custom=[...new Set([...custom,w])];save();$('customWord').value='';parentRender();};
startSession();