'use strict';
const $=id=>document.getElementById(id);
const curriculum={
1:[['кот','🐱'],['мак','🌺'],['сом','🐟'],['сон','😴'],['нос','👃'],['рот','👄'],['рак','🦞'],['лук','🧅'],['кит','🐋'],['рис','🍚'],['мир','🌍'],['сад','🌳'],['суп','🍲'],['сок','🧃'],['сыр','🧀'],['бык','🐂'],['шар','🎈'],['жук','🪲']],
2:[['мама','👩'],['папа','👨'],['лиса','🦊'],['рыба','🐟'],['нога','🦵'],['рука','✋'],['луна','🌙'],['сова','🦉'],['коза','🐐'],['муха','🪰'],['ваза','🏺'],['пила','🪚'],['лупа','🔍'],['вода','💧'],['зима','❄️'],['вата','☁️'],['жаба','🐸'],['нора','🕳️'],['кора','🌳'],['губа','👄'],['мыло','🧼'],['сила','💪'],['пума','🐆']],
3:[['стол','🪑'],['стул','🪑'],['слон','🐘'],['кран','🏗️'],['мост','🌉'],['лист','🍃'],['куст','🌿'],['торт','🎂'],['парк','🌳'],['волк','🐺'],['шарф','🧣'],['зонт','☂️'],['бант','🎀'],['винт','🔩']],
4:[['лампа','💡'],['сумка','👜'],['вилка','🍴'],['палка','🪵'],['банка','🫙'],['маска','🎭'],['карта','🗺️'],['парта','🪑'],['панда','🐼'],['ванна','🛁'],['каска','⛑️'],['марка','✉️'],['булка','🥖'],['буква','🔤'],['труба','📯'],['трава','🌱'],['крупа','🌾'],['слива','🟣'],['плита','🍳']],
5:[['май','🌷'],['рой','🐝'],['чай','🍵'],['край','🏞️'],['сарай','🛖'],['урожай','🌾'],['попугай','🦜']],
6:[['конь','🐴'],['пень','🪵'],['тень','👤'],['соль','🧂'],['ноль','0️⃣'],['моль','🦋'],['уголь','⚫']],
7:[['яма','🕳️'],['юла','🌀'],['ёж','🦔'],['маяк','🗼'],['мяч','⚽'],['лёд','🧊'],['люк','⭕'],['мел','🖍️'],['лес','🌲'],['ряд','👥'],['лён','🌿']]
};
const letters=[['к','кот','🐱'],['о','окно','🪟'],['т','торт','🎂'],['а','арбуз','🍉'],['м','мак','🌺'],['с','сок','🧃'],['н','нос','👃'],['р','рак','🦞'],['у','утка','🦆'],['и','игла','🪡'],['л','лук','🧅'],['п','папа','👨'],['ы','сыр','🧀'],['б','бык','🐂'],['ш','шар','🎈'],['ж','жук','🪲'],['д','дом','🏠'],['в','ваза','🏺'],['з','зонт','☂️'],['г','гусь','🪿'],['х','муха','🪰'],['ф','флаг','🚩'],['ч','чай','🍵'],['ц','цапля','🐦'],['э','эхо','📣'],['й','май','🌷'],['ь','конь','🐴'],['е','мел','🖍️'],['ё','ёж','🦔'],['ю','юла','🌀'],['я','яма','🕳️'],['щ','щука','🐟']];
const vowels='аеёиоуыэюя';
let level=Math.min(7,Math.max(1,Number(localStorage.getItem('ss-curriculum-level')||1))),style=localStorage.getItem('ss-style')||'normal',section=localStorage.getItem('ss-section')||'words';if(style==='hand')style='handLower';
let progress=JSON.parse(localStorage.getItem('ss-progress-v2')||'{}'),letterProgress=JSON.parse(localStorage.getItem('ss-letter-progress-v2')||'{}');
let current=null,usedHint=false,markedThisTurn=false,confirmationTimer=null,sessionWords=[],sessionIndex=0,letterSession=[],letterIndex=0,letterMarked=false;
function st(w){const x=progress[w]||{};return{self:+(x.self||0),mastered:!!x.mastered,masteredAt:+(x.masteredAt||0)};}
function lst(ch){const x=letterProgress[ch]||{};return{self:+(x.self||0),mastered:!!x.mastered,masteredAt:+(x.masteredAt||0)};}
function save(){localStorage.setItem('ss-progress-v2',JSON.stringify(progress));localStorage.setItem('ss-letter-progress-v2',JSON.stringify(letterProgress));}
function needed(w){return [...new Set([...w].filter(ch=>/\p{L}/u.test(ch)))];}
function wordUnlocked(w){return needed(w).every(ch=>lst(ch).mastered);}
function levelWords(n=level){return (curriculum[n]||[]).slice();}
function availableWords(){let a=[];for(let n=1;n<=level;n++)a.push(...levelWords(n));return a.filter(x=>wordUnlocked(x[0]));}
function queue(){const available=availableWords().map(x=>x[0]);let q=JSON.parse(localStorage.getItem('ss-adaptive-queue')||'[]').filter(w=>available.includes(w));while(q.length<5){const fresh=available.find(w=>!q.includes(w)&&!st(w).mastered)||available.find(w=>!q.includes(w));if(!fresh)break;q.push(fresh);}const ready=q.filter(w=>st(w).mastered);if(ready.length>=4){const fresh=available.find(w=>!q.includes(w)&&!st(w).mastered);if(fresh){const oldest=ready.sort((a,b)=>st(a).masteredAt-st(b).masteredAt)[0];q=q.map(w=>w===oldest?fresh:w);}}localStorage.setItem('ss-adaptive-queue',JSON.stringify(q));return q;}
function letterQueue(){const available=letters.map(x=>x[0]);let q=JSON.parse(localStorage.getItem('ss-letter-queue-v2')||'[]').filter(ch=>available.includes(ch));if(!q.length)q=available.slice(0,5);while(q.length<5){const n=available.find(ch=>!q.includes(ch));if(!n)break;q.push(n);}const ready=q.filter(ch=>lst(ch).mastered);if(ready.length>=4){const fresh=available.find(ch=>!q.includes(ch)&&!lst(ch).mastered);if(fresh){const oldest=ready.sort((a,b)=>lst(a).masteredAt-lst(b).masteredAt)[0];q=q.map(ch=>ch===oldest?fresh:ch);}}localStorage.setItem('ss-letter-queue-v2',JSON.stringify(q));return q;}
function shown(w){const lower=w.toLocaleLowerCase('ru');if(style==='upper'||style==='handUpper')return lower.toLocaleUpperCase('ru');if(style==='title'||style==='handTitle')return lower[0].toLocaleUpperCase('ru')+lower.slice(1);return lower;}
function render(w,target=$('word')){target.replaceChildren(...[...shown(w)].map(ch=>{const s=document.createElement('span');s.textContent=ch;s.className=ch.toLowerCase()==='ь'?'sign':vowels.includes(ch.toLowerCase())?'vowel':'consonant';return s;}));target.classList.toggle('hand',style.startsWith('hand'));}
function renderLetter(ch){const el=$('letterCard');el.textContent=shown(ch);el.className='letter-card '+(ch==='ь'?'sign':vowels.includes(ch)?'vowel':'consonant')+(style.startsWith('hand')?' hand':'');}
function speak(text,rate=.72){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='ru-RU';u.rate=rate;speechSynthesis.speak(u);}
function hideConfirmation(){clearTimeout(confirmationTimer);$('confirmation').classList.remove('show');$('readOk').classList.remove('done');}
function resetTurn(){hideConfirmation();usedHint=false;markedThisTurn=false;$('readOk').disabled=false;}
function showSessionWord(){const w=sessionWords[sessionIndex];current=availableWords().find(x=>x[0]===w);if(!current){$('word').textContent='';return;}render(current[0]);$('pic').textContent=current[1];$('pic').hidden=true;$('reward').textContent='';resetTurn();}
function startSession(){sessionWords=queue().slice(0,5);sessionIndex=0;$('finishView').hidden=true;if(section==='words'){$('readingView').hidden=false;if(sessionWords.length)showSessionWord();else{$('word').textContent='';$('pic').hidden=true;$('reward').textContent='Сначала познакомься со звуками';}}}
function finishSession(){hideConfirmation();speechSynthesis?.cancel();$('readingView').hidden=true;$('finishView').hidden=false;}
function audioHelp(){if(!current)return;if(!markedThisTurn){usedHint=true;$('readOk').disabled=true;}speak(current[0],.68);}
function showPicture(){if(!current)return;if(!markedThisTurn){usedHint=true;$('readOk').disabled=true;}$('pic').hidden=false;}
function markIndependent(){if(!current||usedHint||markedThisTurn)return;const s=st(current[0]),was=s.mastered;s.self=Math.min(3,s.self+1);s.mastered=s.self>=3;if(s.mastered&&!was)s.masteredAt=Date.now();progress[current[0]]=s;save();markedThisTurn=true;$('readOk').disabled=true;$('confirmation').textContent=!was&&s.mastered?'Слово освоено':'Засчитано';$('confirmation').classList.add('show');$('readOk').classList.add('done');}
function next(){if(!current||sessionIndex>=sessionWords.length-1){finishSession();return;}sessionIndex++;showSessionWord();}
function currentLetter(){return letters.find(x=>x[0]===letterSession[letterIndex])||letters[0];}
function showLetter(){const x=currentLetter();renderLetter(x[0]);$('letterPicture').textContent=x[2];$('letterPicture').hidden=true;letterMarked=false;$('letterKnown').disabled=false;$('letterKnown').classList.remove('done');}
function startLetterSession(){letterSession=letterQueue().slice(0,5);letterIndex=0;$('letterFinishView').hidden=true;if(section==='letters'){$('lettersView').hidden=false;showLetter();}}
function markLetter(){if(letterMarked)return;const ch=currentLetter()[0],s=lst(ch),was=s.mastered;s.self=Math.min(3,s.self+1);s.mastered=s.self>=3;if(s.mastered&&!was)s.masteredAt=Date.now();letterProgress[ch]=s;save();letterMarked=true;$('letterKnown').disabled=true;$('letterKnown').classList.add('done');}
function nextLetter(){if(letterIndex>=letterSession.length-1){$('lettersView').hidden=true;$('letterFinishView').hidden=false;return;}letterIndex++;showLetter();}
function switchSection(s){section=s;localStorage.setItem('ss-section',s);$('readingView').hidden=$('lettersView').hidden=$('finishView').hidden=$('letterFinishView').hidden=true;$('wordsTab').classList.toggle('on',s==='words');$('lettersTab').classList.toggle('on',s==='letters');s==='words'?startSession():startLetterSession();}
$('help').onclick=audioHelp;$('showPicture').onclick=showPicture;$('readOk').onclick=markIndependent;$('next').onclick=next;$('continue').onclick=startSession;$('letterKnown').onclick=markLetter;$('letterShowPicture').onclick=()=>{$('letterPicture').hidden=false;};$('letterPicture').onclick=()=>speak(currentLetter()[1],.72);$('letterNext').onclick=nextLetter;$('letterContinue').onclick=startLetterSession;$('lettersTab').onclick=()=>switchSection('letters');$('wordsTab').onclick=()=>switchSection('words');
const styleLabels={normal:'абв',title:'Абв',upper:'АБВ',handLower:'абв',handTitle:'Абв',handUpper:'АБВ'};
function styleRender(){$('styleSelect').textContent=styleLabels[style]||'абв';$('styleSelect').classList.toggle('hand-preview',style.startsWith('hand'));document.querySelectorAll('.style-option').forEach(b=>b.classList.toggle('selected',b.dataset.style===style));}
function parentRender(){const q=queue();$('queue').innerHTML=q.length?q.map(w=>`<div class="word-row"><strong>${w}</strong><span class="status">${st(w).mastered?'Освоено':st(w).self+'/3'}</span></div>`).join(''):'<div class="empty">Слова откроются после освоения нужных звуков.</div>';$('mastered').innerHTML=Object.keys(progress).filter(w=>st(w).mastered).map(w=>`<div class="word-row mastered-row"><strong>${w}</strong><span class="status">✓ Освоено</span></div>`).join('')||'<div class="empty">Пока нет освоенных слов.</div>';const lq=letterQueue();$('letterQueue').innerHTML=lq.map(ch=>`<div class="word-row"><strong>${ch.toUpperCase()}</strong><span class="status">${lst(ch).mastered?'Освоено':lst(ch).self+'/3'}</span></div>`).join('');$('masteredLetters').innerHTML=letters.map(x=>x[0]).filter(ch=>lst(ch).mastered).map(ch=>`<div class="word-row mastered-row"><strong>${ch.toUpperCase()}</strong><span class="status">✓ Освоено</span></div>`).join('')||'<div class="empty">Пока нет освоенных звуков.</div>';if($('level'))$('level').value=String(level);styleRender();}
$('parentOpen').onclick=()=>{$('childView').hidden=true;$('parentView').hidden=false;parentRender();};$('parentBack').onclick=()=>{$('parentView').hidden=true;$('childView').hidden=false;switchSection(section);};$('styleSelect').onclick=()=>{$('styleMenu').hidden=!$('styleMenu').hidden;};document.querySelectorAll('.style-option').forEach(b=>b.onclick=()=>{style=b.dataset.style;localStorage.setItem('ss-style',style);styleRender();$('styleMenu').hidden=true;});
if($('level')){$('level').innerHTML=Object.keys(curriculum).map(n=>`<option value="${n}">Level ${n}</option>`).join('');$('level').onchange=e=>{level=+e.target.value;localStorage.setItem('ss-curriculum-level',level);localStorage.removeItem('ss-adaptive-queue');startSession();parentRender();};}
if($('addWord'))$('addWord').closest('.panel').hidden=true;
switchSection(section==='letters'?'letters':'words');