'use strict';
const $=id=>document.getElementById(id);
const banks={ru:{3:[['кот','🐱'],['дом','🏠'],['сок','🧃'],['мак','🌺'],['сыр','🧀'],['кит','🐋'],['мяч','⚽'],['лес','🌲'],['нос','👃'],['лук','🧅']],4:[['мама','👩'],['папа','👨'],['рука','✋'],['лиса','🦊'],['рыба','🐟'],['роза','🌹'],['сова','🦉'],['нога','🦵'],['луна','🌙'],['коза','🐐']],5:[['кошка','🐈'],['шапка','🧢'],['чашка','☕'],['книга','📖'],['лимон','🍋'],['белка','🐿️'],['сумка','👜'],['ложка','🥄'],['банан','🍌'],['арбуз','🍉']]},en:{3:[['cat','🐱'],['dog','🐶'],['sun','☀️'],['pin','📌']],4:[['frog','🐸'],['fish','🐟'],['milk','🥛']],5:[['snake','🐍'],['apple','🍎']]},fr:{3:[['sac','👜'],['lac','🏞️'],['bus','🚌']],4:[['moto','🏍️'],['lune','🌙'],['papa','👨']],5:[['souris','🐭'],['lapin','🐰']]}};
const sounds={ru:[['А','🚌','а'],['Б','🥁','б'],['В','🐺','в'],['Г','🍄','г'],['М','⚽','м']],en:[['A','🍎','a'],['B','⚽','b'],['C','🐱','c'],['D','🐶','d'],['S','☀️','s']],fr:[['A','✈️','a'],['B','⚽','b'],['C','🐱','k'],['D','🎲','d'],['E','🐘','e']]};
let language=localStorage.getItem('readingLanguage')||'ru',level=3,index=0,session=[];
let mastered=JSON.parse(localStorage.getItem('masteredByLanguage')||'{}'),working=JSON.parse(localStorage.getItem('workingByLanguage')||'{}'),queues=JSON.parse(localStorage.getItem('readingQueues')||'{}'),history=JSON.parse(localStorage.getItem('readingHistory')||'[]'),custom=JSON.parse(localStorage.getItem('customWordsByLanguage')||'{}');
const list=o=>o[language]||[], key=()=>language+':'+level;
function save(){localStorage.setItem('masteredByLanguage',JSON.stringify(mastered));localStorage.setItem('workingByLanguage',JSON.stringify(working));localStorage.setItem('readingQueues',JSON.stringify(queues));localStorage.setItem('readingHistory',JSON.stringify(history));}
function pool(){const p=banks[language][level].slice();(custom[language]||[]).forEach(w=>{if([...w].length===level&&!p.some(x=>x[0]===w))p.push([w,'📖']);});return p;}
function activeQueue(){const available=pool().map(x=>x[0]);let q=(queues[key()]||[]).filter(w=>available.includes(w));if(q.length!==5)q=available.slice(0,5);queues[key()]=q;save();return q;}
function rotateQueue(){const q=activeQueue(),ready=q.filter(w=>list(mastered).includes(w));if(ready.length<4)return;const fresh=pool().map(x=>x[0]).find(w=>!q.includes(w)&&!list(mastered).includes(w));if(fresh){queues[key()]=q.map(w=>w===ready[0]?fresh:w);save();}}
function start(){rotateQueue();const p=pool();session=activeQueue().map(w=>p.find(x=>x[0]===w)).filter(Boolean);index=0;draw();}
function draw(){const x=session[index]||session[0];if(!x)return;$('word').textContent=x[0];$('pic').textContent=x[1];$('pic').hidden=true;}
function help(){if(!session[index])return;$('pic').hidden=false;const w=session[index][0];if(!list(working).includes(w)&&!list(mastered).includes(w)){working[language]=[...list(working),w];save();}}
$('helpToggle').onclick=help;$('next').onclick=()=>{const weighted=session.flatMap((x,n)=>Array(list(working).includes(x[0])?3:list(mastered).includes(x[0])?1:2).fill(n));index=weighted[Math.floor(Math.random()*weighted.length)];draw();};
function setWord(w,state){mastered[language]=list(mastered).filter(x=>x!==w);working[language]=list(working).filter(x=>x!==w);if(state==='mastered')mastered[language].push(w);if(state==='working')working[language].push(w);save();rotateQueue();parentLists();}
function row(w,controls){return '<div class="word-row"><strong>'+w+'</strong><span>'+controls+'</span></div>';}
function parentLists(){const all=Object.values(banks[language]).flat().map(x=>x[0]).concat(custom[language]||[]);$('knownList').innerHTML=list(mastered).map(w=>row(w,'<button onclick="moveWord(\''+w+'\',\'working\')">В работу</button>')).join('')||'<p>Пока нет</p>';$('workList').innerHTML=list(working).map(w=>row(w,'<button onclick="moveWord(\''+w+'\',\'mastered\')">Освоено</button><button onclick="moveWord(\''+w+'\',\'new\')">Сделать новым</button>')).join('')||'<p>Пока нет</p>';$('newList').innerHTML=all.filter(w=>!list(mastered).includes(w)&&!list(working).includes(w)).map(w=>row(w,'<button onclick="moveWord(\''+w+'\',\'working\')">В работу</button>')).join('')||'<p>Пока нет</p>';let h=$('historyList');if(!h){h=document.createElement('div');h.id='historyList';h.className='word-list';$('newList').parentElement.insertAdjacentElement('afterend',h);}const recent=history.filter(x=>x.language===language).slice(0,12);h.innerHTML='<h2>Последние попытки</h2>'+(recent.map(x=>row(x.word,x.outcome)).join('')||'<p>Пока нет</p>');}
window.moveWord=setWord;
$('parentOpen').onclick=()=>{document.querySelector('main').hidden=true;$('parentView').hidden=false;parentLists();};$('parentBack').onclick=()=>{$('parentView').hidden=true;document.querySelector('main').hidden=false;start();};
$('addWord').onclick=()=>{const w=$('customWord').value.trim().toLowerCase().replace(/[^\p{L}-]/gu,'');if([...w].length<3)return;custom[language]=[...new Set([...(custom[language]||[]),w])];localStorage.setItem('customWordsByLanguage',JSON.stringify(custom));$('customWord').value='';parentLists();};
const evaluation=document.createElement('section');evaluation.className='word-list';evaluation.innerHTML='<h2>Оценить последнее слово</h2><div class="actions"><button data-o="Сам">Сам</button><button data-o="С помощью">С помощью</button><button data-o="Не читал">Не читал</button></div>';$('parentView').querySelector('main').insertBefore(evaluation,$('parentView').querySelector('h2'));evaluation.querySelectorAll('button').forEach(b=>b.onclick=()=>{const w=session[index]&&session[index][0],o=b.dataset.o;if(!w)return;setWord(w,o==='Сам'?'mastered':'working');history.unshift({word:w,language,level,outcome:o,at:new Date().toISOString()});history=history.slice(0,100);save();parentLists();});
$('language').value=language;$('language').onchange=e=>{language=e.target.value;localStorage.setItem('readingLanguage',language);level=3;start();};
let soundTarget;function speakSound(){if(!soundTarget)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(soundTarget[2]);u.lang=language==='ru'?'ru-RU':language==='en'?'en-GB':'fr-FR';u.rate=.7;speechSynthesis.speak(u);}
function drawSounds(){const a=sounds[language];soundTarget=a[Math.floor(Math.random()*a.length)];$('soundLetter').textContent=soundTarget[0];$('soundPicture').textContent=soundTarget[1];$('soundChoices').replaceChildren(...[...a].sort(()=>Math.random()-.5).map(x=>{const b=document.createElement('button');b.className='sound-choice';b.textContent=x[0];b.onclick=()=>{if(x[0]===soundTarget[0])setTimeout(drawSounds,300);};return b;}));speakSound();}
function showMode(m){const s=m==='sounds';$('exercise').closest('.card').hidden=s;$('soundsView').hidden=!s;$('readingMode').setAttribute('aria-pressed',String(!s));$('soundsMode').setAttribute('aria-pressed',String(s));if(s)drawSounds();else start();}$('readingMode').onclick=()=>showMode('reading');$('soundsMode').onclick=()=>showMode('sounds');$('soundListen').onclick=speakSound;$('soundLetter').onclick=speakSound;start();
